add_library(SDL_IMPORTED_LIB SHARED IMPORTED)
add_library(SDL_MAIN_IMPORTED_LIB SHARED IMPORTED)

set(SDL_DIR ${DEPENDENCIES_DIR}SDL/)
set(SDL2_DLL ${SDL_DIR}bin/SDL2.dll)
set(SDL2_LIB_WIN32 ${SDL_DIR}lib/windows/SDL2.lib)
set(SDL2_MAIN_LIB_WIN32 ${SDL_DIR}lib/windows/SDL2main.lib)

if(WIN32)
	set(SDL2_LIB ${SDL2_LIB_WIN32})
	set(SDL2_MAIN_LIB ${SDL2_MAIN_LIB_WIN32})
endif(WIN32)

set_property(TARGET SDL_IMPORTED_LIB PROPERTY IMPORTED_LOCATION ${SDL2_DLL})
message("SDL DLL = " ${SDL2_DLL})
set_property(TARGET SDL_IMPORTED_LIB PROPERTY IMPORTED_IMPLIB ${SDL2_LIB})

set_property(TARGET SDL_MAIN_IMPORTED_LIB PROPERTY IMPORTED_IMPLIB ${SDL2_MAIN_LIB})